// USER CONSTANTS
//

export const USER_IDENTITIES_ADD = 'USER_IDENTITIES_ADD';
export const USER_IDENTITIES_REMOVE = 'USER_IDENTITIES_REMOVE';

export const USER_IDENTITIES_AVAILABLE = 'USER_IDENTITIES_AVAILABLE';
export const USER_IDENTITIES_UNAVAILABLE = 'USER_IDENTITIES_UNAVAILABLE';
