// LIFECYCLE HOOKS
//

export const LIFECYCLE_APP_ACTIVE = 'LIFECYCLE_APP_ACTIVE';
export const LIFECYCLE_APP_INACTIVE = 'LIFECYCLE_APP_INACTIVE';
export const LIFECYCLE_APP_AUTH_CHECK = 'LIFECYCLE_APP_AUTH_CHECK';
export const LIFECYCLE_APP_READY = 'LIFECYCLE_READY';
